nationalarchives/ds-ohos-wagtail

sass/includes/_record-details.scss
sass/includes/search/_search-results__list-card.scss
sass/ohos/_tags.scss
templates/includes/related-tags.html
templates/includes/tags.html
templates/records/record_detail.html

Ticket URL: [HERITAGE-65](https://national-archives.atlassian.net/browse/HERITAGE-65)
Add related tags section to details page
Visit details page from search results. Eg - `/catalogue/id/C8077549/` and observe tags in right hand column
The table is currently duplicated to show how the mark up should be set with or without the tags as we don't yet have the logic / data for this
[HERITAGE-65]: https://national-archives.atlassian.net/browse/HERITAGE-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-65 Add related tags to details page

---

etna/search/views.py
sass/etna.scss
sass/ohos/_pagination.scss
templates/search/blocks/search_pagination.html

Ticket URL: [HERITAGE-57](https://national-archives.atlassian.net/browse/HERITAGE-57)
Updated pagination style to match those set by `tna-frontend` https://nationalarchives.github.io/tna-frontend/?path=/docs/components-pagination--docs
Observe the new pagination styles on a search results page `/search/catalogue/`
[HERITAGE-57]: https://national-archives.atlassian.net/browse/HERITAGE-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-57 Add updated pagination styles from tna-frontend

---

sass/includes/search/_search-filters.scss
sass/includes/search/_search-hero.scss
sass/includes/search/_search-results__list-card.scss
templates/search/blocks/search_results__list-card--grid.html
templates/search/blocks/search_results__list-card.html

Fix related tags and header search box where regressions had been introduced from updated being pulled from Etna
Check homepage `/` - Header search box
Search page `/search/catalogue/` - Results cards and search header
Details page `/catalogue/id/C8077549/` - Related tags

FIX: CSS changes to fix updates from Etna

---

sass/etna.scss
sass/includes/search/_search-buckets.scss
sass/includes/search/_search-hero.scss
sass/includes/search/_search-sort-view.scss
templates/home/home_page.html
templates/search/blocks/catalogue_search_buckets.html
templates/search/blocks/search_results_hero.html
templates/search/catalogue_search.html

Ticket URL: [HERITAGE-53](https://national-archives.atlassian.net/browse/HERITAGE-53)
Update jumbo tabs on search page to match updated design
Removes top level tabs and new search link
Removes "explainer" sentence above tabs
Visit search page `/search/catalogue/` and check that the tabs work and match the design as expected. Functionality is different on smaller screens so this should also be checked
[HERITAGE-53]: https://national-archives.atlassian.net/browse/HERITAGE-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-53 Update jumbo tabs in search to match OHOS design

---

sass/ohos/_tags.scss
templates/includes/related-tags.html

Ticket URL: [HERITAGE-83](https://national-archives.atlassian.net/browse/HERITAGE-83)
Update tag colours and pluralise related tags labelling
Fixes link font size of tags with link text
Tags are found on the search results cards and related tags on detail pages
`/search/catalogue/`
`/catalogue/id/C8077549/`
[HERITAGE-83]: https://national-archives.atlassian.net/browse/HERITAGE-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-83 Fix tags colour and pluralise related tags labelling

---

templates/search/blocks/search_filters.html

Ticket URL: [HERITAGE-88](https://national-archives.atlassian.net/browse/HERITAGE-88)
Fix filter search button so hover state is still readable
Hover over the search submit button in the filters on `/search/catalogue/`
[HERITAGE-88]: https://national-archives.atlassian.net/browse/HERITAGE-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-88 Fix button style on filter search

---

sass/includes/_record-details.scss

Ticket URL: [HERITAGE-95](https://national-archives.atlassian.net/browse/HERITAGE-95)
Changes to the global page background caused the table stripe to go missing. Setting a darker colour (as per design) resolves this
Details page can be found at `/catalogue/id/C8077549/`
[HERITAGE-95]: https://national-archives.atlassian.net/browse/HERITAGE-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-95 Update record details table stripe colour

---

etna/search/templatetags/search_tags.py

Ticket URL: [HERITAGE-110](https://national-archives.atlassian.net/browse/HERITAGE-110)
Update label from "Catalogue search results" to "Search results".
As this is is tied to some backend logic, this may become obsolete. 
Page can be found at `/search/catalogue/`
[HERITAGE-110]: https://national-archives.atlassian.net/browse/HERITAGE-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-110 Update search results label

---

sass/includes/search/_long-filters.scss

Ticket URL: [HERITAGE-119](https://national-archives.atlassian.net/browse/HERITAGE-119)
Change layout from CSS columns to CSS grid to improve reading order and alignment of long filters
This can be viewed at `/search/catalogue/long-filter-chooser/collection/`
[HERITAGE-119]: https://national-archives.atlassian.net/browse/HERITAGE-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-119 Display filters in a grid on long filters page

---

sass/includes/_record-cta-panel.scss
templates/includes/records/record-cta-panel.html
templates/records/record_detail.html

Ticket URL: [HERITAGE-126](https://national-archives.atlassian.net/browse/HERITAGE-126)
Add "back to search" and "start a new search" links to TNA container on details pages
Adds correct `tna-container` to elements that previously used `container`
Details page can be found here `/catalogue/id/C8077549/`. Links are at the top of the page above the "You are viewing the catalogue description of the following item:" label
[HERITAGE-126]: https://national-archives.atlassian.net/browse/HERITAGE-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

HERITAGE-126 Add back to search links to container on details page

---

etna/ciim/client.py
etna/ciim/tests/test_client.py
etna/ciim/utils.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-135
- API is updated internally to reflect queries made with multiple values of the same filter and across filters
- removed OR operator for collection API query for Community agg, as per Rosetta API updates
- relocated prep filter aggregations to utils
- Query with single values for each filter
- Query with multiple values for each filter
- Query across filters combinations
- Filters Community bucket  : http://127.0.0.1:8000/search/catalogue/
Ex: 
http://127.0.0.1:8000/search/catalogue/?covering_date_from_0=&covering_date_from_1=&covering_date_from_2=1980&covering_date_to_0=&covering_date_to_1=&covering_date_to_2=1999&collection=SWOP&place=Church+Street&q=&sort=&group=community
Follow …

HERITAGE-135: Filters

---

etna/records/converters.py
etna/records/tests/test_id_formats.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-190
Update URL pattern to allow CIIM id with dot.
http://127.0.0.1:8000/search/catalogue/?covering_date_from_0=&covering_date_from_1=&covering_date_from_2=&covering_date_to_0=&covering_date_to_1=&covering_date_to_2=&collection=People%27s+Collection+Wales&q=church&group=community&page=1
http://127.0.0.1:8000/catalogue/id/pcw-22987.0/

HERITAGE-190:update record link

---

etna/records/field_labels.py
etna/records/models.py
etna/records/tests/test_models.py
templates/includes/records/record-details-community.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-196
Following changes made for OSC records to return list(str) instead of str
- Update attribute name subject -> subjects 
http://127.0.0.1:8000/catalogue/id/osc-16002/
http://127.0.0.1:8000/catalogue/id/pcw-41083/

HERITAGE-196:update attribute

---

sass/includes/_record-details.scss
sass/includes/search/_search-results__list-card.scss

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-205
Adjusting overflow style for long descriptions.
Pull branch, check layout of a record with a long description:
http://localhost:8000/catalogue/id/pcw-42868/

H-205-fix-overflow-issue

---

etna/ciim/utils.py
etna/records/models.py
etna/records/tests/test_models.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-207
Allow anchor, new lines into HTML
http://127.0.0.1:8000/search/catalogue/?q=1944+airfield&collection=People%27s+Collection+Wales&covering_date_from_0=&covering_date_from_1=&covering_date_from_2=&covering_date_to_0=&covering_date_to_1=&covering_date_to_2=&per_page=20&sort=&display=list&group=community
http://127.0.0.1:8000/catalogue/id/pcw-42868/

HERITAGE-207: Allow anchor and new line tags

---

etna/ciim/constants.py
etna/records/models.py
etna/search/tests/fixtures/catalogue_search_having_enrichment_tags.json
etna/search/tests/test_views.py
templates/includes/tags.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-262
- Integrates API response named entities in the search results
- Location, Person, Organisation, Miscellaneous will be populated with enriched data (max 1 value) when present
- Other - tag is no longer needed, hence removed.
- Added tests
Tags are present for Collection-SWOP / swop-49008
http://127.0.0.1:8000/search/catalogue/?q=swop-49008&group=community&vis_view=list
http://127.0.0.1:8000/search/catalogue/?q=swop-49008&group=community&vis_view=timeline
http://127.0.0.1:8000/search/catalogue/?q=swop-49008&group=community&vis_view=tag
Tags not present for Collection-People's Collection Wales
http://127.0.0.1:8000/search/catalogue/?&collection=People%27s+Collection+Wales&vis_view=list&group=community
Follow …

HERITAGE-262: Integrate search results with enrichment tag data

---

etna/records/models.py
templates/records/record_detail.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-289
When there is at least one enrichment, show Relate Tags block, otherwise don't
- http://127.0.0.1:8000/catalogue/id/wmk-20508/ - Hide Related tags block
- http://127.0.0.1:8000/catalogue/id/swop-8872/ - (Regression) - show related tags block

HERITAGE-289: details related tags cond

---

templates/search/blocks/search_results__list-card.html

Ticket URL: [HERITAGE-300](https://national-archives.atlassian.net/browse/HERITAGE-300)
Add text truncation to search results cards
Navigate to search results at `/search/catalogue/`
[HERITAGE-300]: https://national-archives.atlassian.net/browse/HERITAGE-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-300 truncate item titles in search results cards

---

templates/search/blocks/search_results__list-card.html

Ticket URL: [HERITAGE-267](https://national-archives.atlassian.net/browse/HERITAGE-267)
Truncate item descriptions in search results cards, ensures HTML elements are closed properly
Search results cards can be found at `/search/catalogue/`
[HERITAGE-267]: https://national-archives.atlassian.net/browse/HERITAGE-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-267 truncate item descriptions in search results cards

---

templates/includes/related-tags.html
templates/includes/tags-wiki.html

Ticket URL: [HERITAGE-298](https://national-archives.atlassian.net/browse/HERITAGE-298)
Move tag term to the same partial that contains the tags loop and add condition to only render label if tags exist
Example page `/catalogue/id/swop-7960/`. Related tags are displayed on the right column. Labels should only display when tags are present
[HERITAGE-298]: https://national-archives.atlassian.net/browse/HERITAGE-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-298 Make related-tags 'sections' conditional

---

etna/ciim/tests/fixtures/record_community.json
etna/records/field_labels.py
etna/records/models.py
etna/records/tests/test_models.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-297
Added, Updated BE API attributes
Details page:
http://127.0.0.1:8000/catalogue/id/mpa-14446/ - provenance
http://127.0.0.1:8000/catalogue/id/swop-7960/ - creator, place_of_deposit, description
http://127.0.0.1:8000/catalogue/id/swop-1076/ - description
Search results:
Query on above id's

HERITAGE-297: add, update BE API attributes

---

etna/records/field_labels.py
templates/includes/records/record-details-community.html

Ticket URL: [HERITAGE-214](https://national-archives.atlassian.net/browse/HERITAGE-214)
Add new table rows for additional attributes on details page
See table at `/catalogue/id/swop-33491/` - I've not been able to find any records containing provenance
[HERITAGE-214]: https://national-archives.atlassian.net/browse/HERITAGE-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-214 Add attributes to details page FE

---

etna/records/models.py
etna/records/views/records.py
etna/search/views.py
templates/records/record_detail.html

Ticket URL: N/A
Issue: 
Record details for TNA/ROA is currently showing only the attributes applicable for community bucket.
The Description in details for TNA/ROA shows html markup.
Fix:
The fix is to show record details for TNA, ROA, and update description to remove html markup same as Etna.
http://127.0.0.1:8000/search/catalogue/?group=tna
http://127.0.0.1:8000/catalogue/id/N13807956/
http://127.0.0.1:8000/search/catalogue/?group=nonTna
http://127.0.0.1:8000/catalogue/id/C14667462/

FIX: Show record details, update description for tna/roa

---

sass/etna.scss
sass/ohos/_tags.scss
sass/ohos/_wikidata-overlays.scss
scripts/src/modules/wikidata-overlays/wikidata-overlays.js
templates/includes/tags-wiki.html
templates/records/record_detail.html
webpack.config.js

Ticket URL: [HERITAGE-305](https://national-archives.atlassian.net/browse/HERITAGE-305)
Add wikidata overlays to detail pages where wikidata is available on each tag. Uses SPARQL rather than the rest API to reduce the request into a single, tiny response
A page containing wikidata overlays can be found at `/catalogue/id/swop-15407/`
[HERITAGE-305]: https://national-archives.atlassian.net/browse/HERITAGE-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-305 Wikidata overlays

---

etna/ciim/client.py
etna/ciim/constants.py
etna/ciim/tests/factories.py
etna/ciim/tests/test_utils.py
etna/ciim/utils.py
etna/records/models.py
etna/search/forms.py
etna/search/templates/search/widgets/search-filter-checkbox-list.html
etna/search/templatetags/search_tags.py
etna/search/tests/test_views.py
etna/search/views.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-291
- handle `group` values from `groupArray` for buckets
- updated label for OHOS collections
- modified api response to prepare for nested choices
- modified dynamic checkbox to handle nested values
- modified checkbox html structure to handle nested values
- modified choice data to handle nested values
- modified api calls to CIIM for nested filter checkboxes
- modified filter labels to handle "parent" checkboxes
- add/update tests
- sorting of collections for tna,roa are removed.
- Prefixed Aggregate alias names are added to the value in the URL for a nested collections `parent-collectionMorrab`, `child-collectionSurrey`
- The collection field is same for all buckets. For OHOS the "collection" maps to "community" …

HERITAGE-291: Nested Checkbox filters - BE

---

etna/search/common.py
etna/search/views.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-328
Added search term param to Visualisation links
Search term = ufo
http://127.0.0.1:8000/search/catalogue/?q=ufo&group=community
List view, Map view, Timeline view and Tag view should contain &q=ufo appended to the link
Click the Visualisation link, the results are updated based on search term

HERITAGE-328:Added search term param to Visualisation links

---

etna/ciim/client.py
etna/ciim/tests/test_utils.py
etna/ciim/utils.py
etna/search/tests/test_views.py
etna/search/views.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-328
- update visualisation view links to include filters
- Map view queries ciim by excluding filters
- enter search and filter via a visualisation view
Ex List view http://127.0.0.1:8000/search/catalogue/?covering_date_from_0=&covering_date_from_1=&covering_date_from_2=1900&covering_date_to_0=&covering_date_to_1=&covering_date_to_2=&collection=People%27s+Collection+Wales&collection=Sharing+Wycombe%27s+Old+Photographs&collection=parent-collectionMorrab%3AMorrab+Photo+Archive&collection=child-collectionMorrab%3AAngove+Collection&collection=child-collectionMorrab%3AMiscellaneous+Photos&q=royal&sort=&vis_view=list&group=community
- Clicking on any of the Visualisation views retains the search criteria - Ex click on List …

HERITAGE-328: update visualisation view links to include filters

---

etna/search/forms.py
etna/search/templatetags/search_tags.py
etna/search/tests/test_search_tags.py
etna/search/tests/test_views.py
etna/search/views.py
templates/search/blocks/search_filters.html
templates/search/blocks/search_results_hero.html
templates/search/blocks/search_results_tag_frequency.html
templates/search/blocks/search_sort_and_view_options.html

Ticket URL:  https://national-archives.atlassian.net/browse/HERITAGE-347
- Add `chart_data_type` form element, and hidden fields across all forms
- Update Filter by/Category/Chart Data Type/Tag type url links
- to handle tag selection with all filter params
- to handle tag deselection
- Navigate to [Tag view](http://127.0.0.1:8000/search/catalogue/?group=community&vis_view=tag) - add search query, refine filters
- Select a [Tag to filter by](http://127.0.0.1:8000/search/catalogue/?group=community&vis_view=tag&chart_data_type=PER) - page should reload and any search filters should be retained
- Unselect the Tag that is filtered - should return to state before selecting the Tag
Follow [docs\developer-guide\contributing.md](https://nationalarchives.github.io/ds-wagtail/developer-guide/contrib …

HERITAGE-347: BE updates for Tag selection

---

etna/ciim/constants.py
etna/search/tests/test_views.py
etna/search/views.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-348
- Update the 4 template var for enrichment aggregations to one variable. 
i.e. `enrichment_aggs` 
The var contain enrichment aggregation data which will be used to replace the static data file for Tag visualisation. These are update on each page load.
- Updated tests
`enrichment_aggs`  to be integrated into FE

HERITAGE-348: BE tag visualisation - updated to one template var

---

etna/ciim/constants.py
etna/ciim/tests/test_utils.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-375
- Adds new config for nested filters for WMK in `NESTED_CHECKBOX_VALUES_AGGS_NAMES_MAP`
- Adds tests
http://127.0.0.1:8000/search/catalogue/?group=community&vis_view=list&collection=parent-collectionWMK%3AMilton+Keynes+City+Discovery+Centre&collection=child-collectionWMK%3AWomen+who+made+Milton+Keynes

HERITAGE-375: nested filters wmk

---

templates/search/blocks/search_results_tag_frequency.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-355
Change “Filter by:” to “Refine by category:”
Add label text for accessibility:
Location = “Category: Location”
Person = “Category: Person”
Organisation = “Category: Organisation”
Miscellaneous = “Category: Miscellaneous”
Run locally and check text change.
Inspect the top level buttons that they are now as a <label> element for accessibility.

HERITAGE-355- changing-text-and-adding-labels

---

etna/ciim/constants.py
etna/records/converters.py
etna/records/tests/test_id_formats.py
etna/records/tests/test_models.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-381
- Configures new ciim id
- Update tests
- **NOTE**: CAIN Archive has multiple ciim prefixed ids ex sid-0 (Community level), me-0 (Collection level)
Dev notes:
ciim id = `me-{id}`
"Collection" level ciim id => `me-0`
me-api data shows under SID
Nested archive/collection abbrev => `SID` (Top level is Community)
Nested filter name => CAIN Archive - Conflict and Politics in Northern Ireland
"Community" level ciim id => `sid-0`
aggs alias => `collectionCain`
filter alias => `collectionOhos`
- Navigate to search
- Select "CAIN Archive - Conflict and Politics in Northern Ireland" and Update filter - It should show as nested collection containing "The Northern Ireland Political Ephemera Collection of Peter Moloney"
- Select …

HERITAGE-381: integrate moloney data

---

.platform.app.yaml

Ticket URL: NA
Retrofit fix from `OHOS` branch
Fixes deploy issue to plaform.sh
webpack 5.91.0 compiled with 3 warnings in 18537 ms
W: Traceback (most recent call last):
W:   File "/app/.global/bin/poetry", line 5, in <module>
W:     from poetry.console.application import main
W: ModuleNotFoundError: No module named 'poetry'
E: Error building project: Step failed with status code 1.
E: Error: Unable to build application, aborting.
Deploy to platform.sh

Retrofit Fix from OHOS:deploy fix for ModuleNotFoundError: No module named poetry

---

sass/ohos/_search-results-map.scss

Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/HERITAGE/issues/HERITAGE-386
Height / padding adjustment to warning icon (fix).
Run branch locally 
Check a details page that has a named entity associated with it, 
Example : http://localhost:8000/catalogue/id/pcw-779721/

HERITAGE-386-warning-icon-on-details-page

---

sass/includes/search/_search-results.scss
scripts/src/modules/search/mobile-filter-expander-enhanced.js

Ticket URL: https://national-archives.atlassian.net/jira/software/c/projects/HERITAGE/issues/HERITAGE-410
Changing the breakpoint so mobile filters appear at 992px
Check that filter view changes at 992px width

HERITAGE-410-filters-breakpoint

---

etna/search/tests/fixtures/community_enrichment_aggs_no_entries_search_filter_collection.json
etna/search/tests/fixtures/community_enrichment_aggs_no_entries_search_term.json
etna/search/tests/test_views.py
etna/search/views.py
templates/search/blocks/search_results_tag_frequency.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-337
Add template var `has_enrichment_aggs_entries` returns bool and tests for enrichment agg entries. 
The var will enable its usage to show no results message for query that returns enrichment aggs without entries attribute.
- http://127.0.0.1:8000/search/catalogue/?q=qwert&vis_view=tag&group=community
- http://127.0.0.1:8000/search/catalogue/?collection=parent-collectionSurrey%3ASurrey+History+Centre&vis_view=tag&group=community

HERITAGE-337:Add template var and tests for enrichment agg entries

---

sass/includes/search/_search-visualisation-nav.scss
templates/search/blocks/search_results_timeline_century.html
templates/search/blocks/search_results_timeline_per_century.html
templates/search/blocks/search_results_timeline_single_decade.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-371
Changes to Timeline view.
- Remove teal bar
- Change text in info box to “This view shows the volume of dated items over time. Types of date used may vary.”
Check changes visually

H-371-Timeline-FE-changes

---

etna/ciim/constants.py
etna/ciim/tests/test_utils.py
etna/records/converters.py
etna/records/tests/test_id_formats.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-420
Configures new ciim id
Configures new collection
Update tests
Dev notes:
ciim id = aoc-{id}
Nested archive/collection abbrev => AOC
Nested filter name => `Accounts of the Conflict`
"Community" level ciim id => aoc-0
aggs alias => `collectionConflict`
filter alias => `collectionOhos`
- Navigate to search
- Select `Accounts of the Conflict` and Update filter - It should show as nested collection
- Select a record from search results - It should show details page.

heritage-420: integrate aoc filter record

---

etna/search/forms.py
etna/search/tests/test_views.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-423
Remove count label for OHOS see all collections links
- Filter a nested collection having [see all link](http://127.0.0.1:8000/search/catalogue/?covering_date_from_0=&covering_date_from_1=&covering_date_from_2=&covering_date_to_0=&covering_date_to_1=&covering_date_to_2=&collection=parent-collectionMorrab%3AMorrab+Photo+Archive&q=royal&sort=&vis_view=list&group=community)
- Regression test see all link - with search term, filters, long filters

HERITAGE-423:remove count label from see all

---

scripts/src/modules/timeline/century.js
scripts/src/modules/timeline/decade.js
scripts/src/modules/timeline/timeline.js

Ticket URL: [HERITAGE-319]
Fixes the decade/year when clicking into the timeline, e.g. clicking 1900 would show 100 200 300, when it should be 1910, 1920, 1930
Now when it is clicked, it will show the expected result.
[HERITAGE-319]: https://national-archives.atlassian.net/browse/HERITAGE-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-319: Fix timeline index
