scripts/src/gtm-script.js
templates/includes/gtm-no-script.html
templates/includes/gtm-script.html

Ticket URL: [HERITAGE-67](https://national-archives.atlassian.net/browse/HERITAGE-67)
Update Google Analytics property for OHOS
[HERITAGE-67]: https://national-archives.atlassian.net/browse/HERITAGE-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-67 Update Google Analytics property for OHOS

---

templates/home/home_page.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-6
- Following https://github.com/nationalarchives/ds-ohos-wagtail/pull/8
- remove unused fields
In the ticket.

HERITAGE-6: prep home page remove unused fields

---

fabfile.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-75
Update staging app instance of plaform.sh
fab pull-staging-data

HERITAGE-75: update stg instance

---

scripts/src/gtm-script.js
templates/includes/gtm-no-script.html
templates/includes/gtm-script.html

Ticket URL: [HERITAGE-79](https://national-archives.atlassian.net/browse/HERITAGE-79)
Update tracking code to use correct code. Was previously using incorrect tracking ID
[HERITAGE-79]: https://national-archives.atlassian.net/browse/HERITAGE-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-79 Update tracking to use correct code

---

sass/etna.scss
sass/includes/search/_search-filters.scss

Ticket URL: NA
This issue followed when syncing `ds-ohos-wagtail`-`develop` (OHOS) with upstream `ds-wagtail`-`develop` (ETNA)
https://github.com/nationalarchives/ds-wagtail/pull/1340 helped to identify and fix
- done some re ordering of elements
CSS issue:
```
sass/etna.scss
145:1  ✖  Unexpected invalid position @import rule  no-invalid-position-at-import-rule
157:1  ✖  Unexpected invalid position @import rule  no-invalid-position-at-import-rule
158:1  ✖  Unexpected invalid position @import rule  no-invalid-position-at-import-rule
159:1  ✖  Unexpected invalid position @import rule  no-invalid-position-at-import-rule
160:1  ✖  Unexpected invalid position @import rule  no-invalid-position-at-import-rule
161:1  ✖  Unexpected invalid position @import rule  no-invalid-position-at-import-rule …
```

FIX: lint css issues

---

etna/search/tests/test_views.py
templates/search/blocks/no_results.html
templates/search/blocks/no_results_catalogue_website.html

Ticket URL: [HERITAGE-122](https://national-archives.atlassian.net/browse/HERITAGE-122)
Update results page text to meet new requirements
Visit search page `/search/catalogue/` and enter a query that returns no results
[HERITAGE-122]: https://national-archives.atlassian.net/browse/HERITAGE-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-122 Change text on no results page

---

sass/includes/search/_search-filters.scss

Ticket URL: 
Fix merge lint issue https://github.com/nationalarchives/ds-ohos-wagtail/actions/runs/7614477684/job/20736827566
```
Checking formatting...
All matched files use Prettier code style!
sass/includes/search/_search-filters.scss
70:5  ✖  Unexpected duplicate selector ".search-filters__submit", first used at line 50  no-duplicate-selectors
1 problem (1 error, 0 warnings)
```

fix merge lint issue

---

templates/search/blocks/search_filters.html

Ticket URL: 
- restore date that was updated conditionally by sync - merge conflicts 
- remove unwanted code comments, website filters - etna
- updated conditions for 
http://127.0.0.1:8000/search/catalogue/?covering_date_from_0=&covering_date_from_1=&covering_date_from_2=1999&covering_date_to_0=&covering_date_to_1=&covering_date_to_2=2000&place=Church+Street&q=&group=community

CHORE: Fix restore date filter

---

sass/etna.scss
sass/includes/search/_search-buckets.scss
sass/includes/search/_search-sort-view.scss
sass/includes/search/_search-visualisation-nav.scss
templates/search/blocks/catalogue_search_buckets.html
templates/search/blocks/visualisation_menu.html
templates/search/catalogue_search.html

Ticket URL: [HERITAGE-204](https://national-archives.atlassian.net/browse/HERITAGE-204)
Built secondary navigation displaying List, Map, Timeline and Tag views
This menu can be seen on the catalogue search page `/search/catalogue/`. Styles have been added for all breakpoints
[HERITAGE-204]: https://national-archives.atlassian.net/browse/HERITAGE-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HERITAGE-204 Build secondary navigation for data-visualisation options

---

Dockerfile
dev/Dockerfile

Ticket URL: NA
Update to version tna-python-django:0.2.3 before sync  is applied and tested from Etna as it has changes - Ex Wagtail upgrade, new tna-build
http://127.0.0.1:8000/

CHORE: Update to version tna-python-django:0.2.3

---

etna/records/converters.py
etna/records/tests/test_id_formats.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-256
Update search results to show links for mpa ciim id format
http://127.0.0.1:8000/search/catalogue/?collection=Angove+Collection&group=community
http://127.0.0.1:8000/search/catalogue/?collection=Classic+Postcard+Collection&group=community
http://127.0.0.1:8000/search/catalogue/?collection=Collins%20Shipwreck%20Collection&group=community
http://127.0.0.1:8000/search/catalogue/?collection=James%20Downing%20Collection&group=community
http://127.0.0.1:8000/search/catalogue/?collection=Richards%20Collection&group=community
http://127.0.0.1:8000/search/catalogue/?collection=Serena%20Wadham%20Archive&group=community
http://127.0.0.1:8000/search/catalogue/?collection=Stanley%20Opie%20Archaeology&group=community
Follow …

HERITAGE-256: Update search results to show links for mpa ciim id format

---

scripts/src/modules/tag-frequency/tag-frequency-chart.js

Ticket URL:  https://national-archives.atlassian.net/browse/HERITAGE-279
Updating svg in Tag view
Run locally and test:
http://127.0.0.1:8000/search/catalogue/?group=community&vis_view=tag&chart_selected=Priory+Ave+LOC&chart_selected=High+Street+LOC

svg amendment

---

etna/ciim/constants.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-278
Changing the text of the buckets
Run locally and check labels for buckets

HERITAGE-278-update-to-bucket-labels

---

sass/includes/_card-groups.scss

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-177
Style change or homepage links
Where possible, provide guidance to help your reviewer
Run locally, check visually

HERITAGE-177-link-colour-change

---

templates/includes/records/record-details-community.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-263
Enable Item URL link in details page
http://127.0.0.1:8000/catalogue/id/pcw-548524/

HERITAGE-263:Enable Item url link

---

sass/includes/_card-groups.scss

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-177
Changing links colour to black
Run locally, check homepage 
http://127.0.0.1:8000/

Heritage-177-links

---

sass/includes/_record-details.scss
templates/includes/related-tags.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-200
Adding in a warning box on related tags
Run branch locally, check visually
http://127.0.0.1:8000/catalogue/id/wmk-20479/

Heritage-200-related-tags-ai-warning

---

templates/includes/related-tags.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-200
Small copy adjustment
Check changes to copy

Heritage-200-copy-adjustment

---

etna/ciim/tests/fixtures/record_community.json
etna/records/field_labels.py
etna/records/models.py
etna/records/tests/test_models.py

Ticket URL: 
https://national-archives.atlassian.net/browse/HERITAGE-297
https://national-archives.atlassian.net/browse/HERITAGE-214
update place of deposit to repository
Add attribute to FE
http://127.0.0.1:8000/catalogue/id/swop-1076/

HERITAGE-297:update attr place of deposit to repository

---

sass/ohos/_tag-frequency-chart.scss
templates/search/blocks/search_results_tag_frequency.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-327
Changing the behaviour of the Apply filters / Clear filters button 
Check the behaviour of the filter buttons

HERITAGE-327-behaviour change for Apply filters / Clear filters button.

---

sass/includes/search/_search-filters.scss

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-316
remove bullet point
Add indent to Collections within Community Archives
Perform a search
Select 'Morrab' and 'Surrey' collections, update
check layout of children checkboxes.
Where possible, provide guidance to help your reviewer

HERITAGE-316 nested filters styling

---

etna/ciim/client.py
etna/ciim/constants.py
etna/ciim/tests/test_utils.py
etna/ciim/utils.py
etna/search/forms.py
etna/search/templates/search/widgets/search-filter-checkbox-list.html
etna/search/templatetags/search_tags.py
etna/search/tests/fixtures/community_nested_filters.json
etna/search/tests/test_views.py
etna/search/views.py
templates/search/long_filter_options.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-260
- `NESTED_CHECKBOX_VALUES_AGGS_NAMES_MAP` - config includes API long filter aggs
- sets see more url for nested collections and long filters
- integrates API for long filters and long filter choices
- updates long filters view
- some refactoring's
- add, update tests
See more url
http://127.0.0.1:8000/search/catalogue/?covering_date_from_0=01&covering_date_from_1=01&covering_date_from_2=1900&covering_date_to_0=&covering_date_to_1=&covering_date_to_2=&collection=Sharing+Wycombe%27s+Old+Photographs&collection=parent-collectionMorrab%3AMorrab+Photo+Archive&collection=parent-collectionSurrey%3ASurrey+History+Centre&collection=child-collectionSurrey%3ABYFLEET+ORAL+HISTORY+GROUP%3A+INTERVIEWS+WITH+BYFLEET+RESIDENTS&q=and&sor …

HERITAGE-260: OHOS Long filters

---

sass/ohos/_search-results-map.scss
templates/search/blocks/search_results_map.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-362
Changing text and positioning of map information.
Run locally
Check changes against the ticket.
Where possible, provide guidance to help your reviewer

HERITAGE-362-map-information

---

etna/ciim/constants.py
etna/ciim/tests/test_utils.py
etna/records/converters.py
etna/records/tests/test_id_formats.py

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-380
- Configures new ciim id
- Configures new collection
- Update tests
Dev notes
ciim id = `sid-{id}`
Nested archive/collection abbrev => `SID`
Nested filter name => `CAIN Archive - Conflict and Politics in Northern Ireland`
"Community" level ciim id => `sid-0`
aggs alias => `collectionCain`
filter alias => `collectionOhos`
- Navigate to search
- Select "CAIN Archive - Conflict and Politics in Northern Ireland" and Update filter - It should show as nested collection
- Select a record from search results - It should show details page.
Follow [docs\infra\environments.md](https://nationalarchives.github. …

HERITAGE-380 integrate sutton data

---

sass/includes/home-refresh.scss
templates/home/home_page.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-411
Adjusting the breakpoints on the banner to make it responsive on mobile views
In responsive mode check that the banner does not split across viewports

H-411-graphQL-banner-mobile-fixes

---

scripts/src/modules/timeline/decade.js

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-319
Update to the 3rd timeline view to show distribution of records within a decade
go through the three views - initial, century, decade
try with search term i.e 'Sheep'
try with Collection Filters selected i.e 'Morrab Photo Archive'
Check performance.

Heritage-319-timeline-per-decade

---

templates/includes/footer.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-425
Removal Freedom of Information text and link from footer
Check footer

Heritage-425 foi-link-removal

---

etna/records/field_labels.py
etna/records/models.py
templates/includes/records/record-details-community.html

Ticket URL: https://national-archives.atlassian.net/browse/HERITAGE-442
Add author record attribute to details page
http://127.0.0.1:8002/catalogue/id/pcw-12/

HERITAGE-442: add author

---

templates/includes/footer.html

Updating the footer links to point to : https://ohos-zgoyvpy-rasrzs7pi6sd4.uk-1.platformsh.site/using-our-website/
Run locally
Check links

footer links update
